# Site settings
title: Professional People: James Roseman
email: hi@jamesroseman.com
description: > # this means to ignore newlines until "baseurl:"
  The thoughts, theories, and pet projects that live inside 
  the mind of an author turned musician turned programmer. I 
  tend to eat well, travel often, and act recklessly, and you can 
  follow all my many adventures here.
baseurl: "/personal-site" # the subpath of your site, e.g. /blog/
url: "http://jamesroseman.com" # the base hostname & protocol for your site
twitter_username: jamesroseman
github_username:  jamesroseman

# Build settings
markdown: kramdown
